name: ci-js
on:
  pull_request:
    branches:
      - main
jobs:
  check-application:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}